name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run the Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./publish/* C:/inetpub/wwwroot/ -Recurse -Force
        iisreset /start
